
<h1>FMS landing page</h1>

<div class="row">
    <div class="span3">Database Server Running</div><div class="span9"><?php echo $this->json->isDBSAvailable ?></div>
</div>
<div class="row">
    <div class="span3">Connected Clients</div><div class="span9"><?php echo $this->json->clients ?></div>
</div>
<div class="row">
    <div class="span3">Files</div><div class="span9"><?php echo $this->json->files ?></div>
</div>