<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('FMS Web')?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->baseUrl('/img/favicon.ico')))
                        ->prependStylesheet($this->baseUrl('/css/bootstrap-responsive.min.css'))
                        ->prependStylesheet($this->baseUrl('/css/style.css'))
                        ->prependStylesheet($this->baseUrl('/css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->appendFile($this->baseUrl('/js/html5.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->appendFile($this->baseUrl('/js/bootstrap.min.js'))
                                      ->appendFile($this->baseUrl('/js/jquery.min.js')) ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->baseUrl('/') ?>">FMS Web</a>
                    <div class="nav-collapse collapse">

                        <?php 
                        foreach ($this->navbar() as $key => $nav)
                        {
                        	echo '<ul class="nav">
                            <li '.$nav['class'].'><a href="'.$nav['Path'].'">'.$key.'</a></li>
                        	</ul>';
                        }
                        ?>
                        
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->layout()->content; ?>
            <hr>
            <footer>
                
            </footer>
        </div> <!-- /container -->
        <?php echo $this->headScript() ?>
    </body>
</html>
